"""
CFO Command Center — Batch Processing Worker

Runs scheduled batch analysis jobs:
  - Daily full agent cycle
  - Weekly executive report
  - Month-end close analysis

Can be triggered via cron, scheduler, or API endpoint.

Usage:
    python -m src.workers.batch_worker --mode daily
    python -m src.workers.batch_worker --mode weekly
    python -m src.workers.batch_worker --mode month-end
"""

import json
import logging
import argparse
from datetime import datetime, timezone

from ..config import NOTION_TOKEN, PAGE_CFO_CENTER
from ..notion_client import NotionClient, to_rich_text
from ..agents.working_capital import WorkingCapitalAgent
from ..agents.cash_flow import CashFlowAgent
from ..agents.payment_optimization import PaymentOptimizationAgent
from ..agents.vendor_risk import VendorRiskAgent

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s"
)
logger = logging.getLogger("batch_worker")


def _rtext(text):
    """Shorthand for Notion rich_text block value."""
    return to_rich_text(text)


class BatchWorker:
    """Scheduled batch processing for CFO analysis jobs."""

    def __init__(self, client: NotionClient):
        self.client = client

    def run_daily(self) -> dict:
        """Run all 4 finance agents, generate daily brief, write to Notion."""
        logger.info("=== DAILY BATCH JOB START ===")
        now = datetime.now(timezone.utc)
        results = {}

        agents = {
            "working_capital": WorkingCapitalAgent(self.client),
            "cash_flow": CashFlowAgent(self.client),
            "payment_optimization": PaymentOptimizationAgent(self.client),
            "vendor_risk": VendorRiskAgent(self.client),
        }

        for name, agent in agents.items():
            try:
                results[name] = agent.run()
                results[name]["status"] = "success"
            except Exception as e:
                logger.error(f"{name} agent failed: {e}")
                results[name] = {"status": "error", "message": str(e)}

        self._write_daily_brief(results, now)
        logger.info("=== DAILY BATCH JOB COMPLETE ===")
        return {"mode": "daily", "timestamp": now.isoformat(), "results": results}

    def run_weekly(self) -> dict:
        """Run all agents + executive summary with week-over-week comparison."""
        logger.info("=== WEEKLY BATCH JOB START ===")
        now = datetime.now(timezone.utc)
        results = self.run_daily()

        weekly_blocks = [
            {"object": "block", "type": "divider", "divider": {}},
            {"object": "block", "type": "heading_1",
             "heading_1": {"rich_text": _rtext(f"Weekly Executive Report — {now.strftime('%Y-%m-%d')}")}},
            {"object": "block", "type": "callout",
             "callout": {
                 "icon": {"emoji": "📊"},
                 "rich_text": _rtext("Automated weekly analysis generated by CFO Command Center AI agents"),
             }},
        ]

        action_items = self._identify_action_items(results)
        if action_items:
            weekly_blocks.append({
                "object": "block", "type": "heading_2",
                "heading_2": {"rich_text": _rtext("CFO Action Items")},
            })
            for item in action_items:
                emoji = {"critical": "🔴", "warning": "🟡", "info": "🔵"}.get(item["severity"], "⚪")
                weekly_blocks.append({
                    "object": "block", "type": "bulleted_list_item",
                    "bulleted_list_item": {
                        "rich_text": _rtext(f"{emoji} [{item['severity'].upper()}] {item['title']} — {item['detail']}")
                    },
                })

        weekly_blocks.append({
            "object": "block", "type": "paragraph",
            "paragraph": {"rich_text": _rtext(f"Report generated: {now.strftime('%Y-%m-%d %H:%M UTC')}")},
        })

        self.client.append_blocks(PAGE_CFO_CENTER, weekly_blocks)
        logger.info("=== WEEKLY BATCH JOB COMPLETE ===")
        return {"mode": "weekly", "timestamp": now.isoformat(), "action_items": len(action_items)}

    def run_month_end(self) -> dict:
        """Run all agents + month-end close report."""
        logger.info("=== MONTH-END BATCH JOB START ===")
        now = datetime.now(timezone.utc)
        results = self.run_daily()

        month_blocks = [
            {"object": "block", "type": "divider", "divider": {}},
            {"object": "block", "type": "heading_1",
             "heading_1": {"rich_text": _rtext(f"Month-End Close Report — {now.strftime('%B %Y')}")}},
            {"object": "block", "type": "callout",
             "callout": {
                 "icon": {"emoji": "🗓️"},
                 "rich_text": _rtext("Automated month-end close analysis. Review all action items before closing."),
             }},
        ]

        wc = results.get("results", {}).get("working_capital", {})
        if wc.get("status") == "success":
            month_blocks.append({
                "object": "block", "type": "heading_2",
                "heading_2": {"rich_text": _rtext("Key Month-End Metrics")},
            })
            for label in [
                f"Cash Position: ${wc.get('cash', 0):,.0f}",
                f"CCC: {wc.get('ccc', 'N/A')} days ({wc.get('trend', 'N/A')})",
                f"Net Working Capital: ${wc.get('nwc', 0):,.0f}",
            ]:
                month_blocks.append({
                    "object": "block", "type": "bulleted_list_item",
                    "bulleted_list_item": {"rich_text": _rtext(label)},
                })

        po = results.get("results", {}).get("payment_optimization", {})
        if po.get("status") == "success":
            month_blocks.append({
                "object": "block", "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": _rtext(
                    f"Payment Optimization Savings: ${po.get('total_discount_savings', 0):,.0f} captured this period"
                )},
            })

        vr = results.get("results", {}).get("vendor_risk", {})
        if vr.get("status") == "success":
            month_blocks.append({
                "object": "block", "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": _rtext(
                    f"Vendors at Risk: {vr.get('at_risk_count', 0)} (${vr.get('total_spend_at_risk', 0):,.0f} spend exposed)"
                )},
            })

        month_blocks.append({
            "object": "block", "type": "paragraph",
            "paragraph": {"rich_text": _rtext(f"Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}")},
        })

        self.client.append_blocks(PAGE_CFO_CENTER, month_blocks)
        logger.info("=== MONTH-END BATCH JOB COMPLETE ===")
        return {"mode": "month-end", "timestamp": now.isoformat()}

    def _write_daily_brief(self, results: dict, now: datetime):
        """Write a concise daily brief to the CFO page."""
        blocks = [
            {"object": "block", "type": "divider", "divider": {}},
            {"object": "block", "type": "heading_2",
             "heading_2": {"rich_text": _rtext(f"Daily Brief — {now.strftime('%Y-%m-%d')}")}},
            {"object": "block", "type": "callout",
             "callout": {
                 "icon": {"emoji": "📋"},
                 "rich_text": _rtext(
                     f"Automated daily analysis. "
                     f"{sum(1 for r in results.values() if r.get('status') == 'success')}/4 agents completed."
                 ),
             }},
        ]

        wc = results.get("working_capital", {})
        if wc.get("status") == "success":
            blocks.append({
                "object": "block", "type": "paragraph",
                "paragraph": {"rich_text": _rtext(
                    f"Cash: ${wc.get('cash', 0):,.0f} | CCC: {wc.get('ccc', 'N/A')}d ({wc.get('trend', 'N/A')}) | "
                    f"NWC: ${wc.get('nwc', 0):,.0f}"
                )},
            })

        cf = results.get("cash_flow", {})
        if cf.get("status") == "success":
            blocks.append({
                "object": "block", "type": "paragraph",
                "paragraph": {"rich_text": _rtext(
                    f"13-Week Net: ${cf.get('net_position', 0):,.0f} | "
                    f"Min Closing: ${cf.get('min_closing_balance', 0):,.0f} | "
                    f"Alerts: {len(cf.get('alerts', []))}"
                )},
            })

        po = results.get("payment_optimization", {})
        if po.get("status") == "success":
            blocks.append({
                "object": "block", "type": "paragraph",
                "paragraph": {"rich_text": _rtext(
                    f"Payment Savings: ${po.get('total_discount_savings', 0):,.0f} | "
                    f"Early Pay: {po.get('payments_to_early_pay', 0)}/{po.get('total_payments', 0)} payments"
                )},
            })

        vr = results.get("vendor_risk", {})
        if vr.get("status") == "success":
            blocks.append({
                "object": "block", "type": "paragraph",
                "paragraph": {"rich_text": _rtext(
                    f"Vendors at Risk: {vr.get('at_risk_count', 0)} | "
                    f"Spend at Risk: ${vr.get('total_spend_at_risk', 0):,.0f} | "
                    f"Contract Warnings: {vr.get('contract_warnings_count', 0)}"
                )},
            })

        self.client.append_blocks(PAGE_CFO_CENTER, blocks)
        logger.info("Daily brief written to CFO page")

    def _identify_action_items(self, results: dict) -> list[dict]:
        """Identify items requiring CFO attention."""
        items = []
        raw = results.get("results", results)

        cf = raw.get("cash_flow", {})
        for alert in cf.get("alerts", []):
            items.append({
                "severity": alert["severity"].lower(),
                "title": f"Cash Flow: {alert['week']}",
                "detail": alert["message"][:150],
            })

        vr = raw.get("vendor_risk", {})
        for v in vr.get("at_risk", []):
            items.append({
                "severity": "warning",
                "title": f"Vendor Risk: {v['vendor']}",
                "detail": f"Risk score {v['risk_score']:.0f}/100, OTD {v['otd']:.0%}, ${v['spend']:,.0f} spend",
            })

        wc = raw.get("working_capital", {})
        for rec in wc.get("recommendations", []):
            if any(kw in rec for kw in ("URGENT", "WARNING", "CRITICAL")):
                items.append({"severity": "warning", "title": "Working Capital", "detail": rec[:150]})

        severity_order = {"critical": 0, "warning": 1, "info": 2}
        items.sort(key=lambda x: severity_order.get(x["severity"], 3))
        return items[:10]


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CFO Command Center — Batch Worker")
    parser.add_argument("--mode", choices=["daily", "weekly", "month-end"], default="daily",
                        help="Batch job mode (default: daily)")
    args = parser.parse_args()

    client = NotionClient(token=NOTION_TOKEN)
    worker = BatchWorker(client)

    if args.mode == "daily":
        result = worker.run_daily()
    elif args.mode == "weekly":
        result = worker.run_weekly()
    elif args.mode == "month-end":
        result = worker.run_month_end()

    print(json.dumps(result, indent=2, default=str))
